repos:
  - repo: local
    hooks:
      - id: make-fmt
        name: make fmt
        entry: make fmt
        language: system
        types: [go]

      - id: make-lint
        name: make lint
        entry: make lint
        language: system
        pass_filenames: false

      - id: make-test
        name: make test
        entry: make test
        language: system
        pass_filenames: false
